### ISSUE TITLE
EPIC: get the MVP ready

### ISSUE THREAD

**Issue by AnnaKahnRaspPi** [RaspberryPiFoundation/editor-ui#110]
we are going to build a thing and not worry too much if it's wrong.

### pre projects beta launch - 
- [x] #137 style the editor pane
- [x]  #114  settings menu 
- [x] #144 
- [x] [make the web component work in the projects site](https://github.com/RaspberryPiFoundation/editor-ui/issues/181)
- [x] #138 display the list of files in the left hand pane
- [x] #163 
- [ ] #139 file CRUD in left hand pane
- [x] #161 
- [x] [fix the bug where your code disappears if you log in](https://github.com/RaspberryPiFoundation/editor-ui/issues/141)

### astro pi - 1 sprint minus the blob
- [x] give the web component the option to enable the senseHAT on page load
- [x] style the editor component
- [x] style the senseHAT astro pi model pane
- [x] blob

### post projects beta launch
- [ ] get things to stack nicely on mobile
- [ ] rest of rest of menus
- [ ] sharing
- [ ] full screen
- [ ] fix the syntax highlighting colours for accessibility
- [ ] visual input indicator
- [ ] style the senseHAT model
- [ ] individual file download
- [ ] whole project download
- [ ] abuse report function - needs more thought
- [ ] sharing button (only on main editor) -more thinking needed
- [ ] #109 JS library shims
