### ISSUE TITLE
Issues with copying code from output into input

### ISSUE THREAD

**Issue by maddyjoe** [RaspberryPiFoundation/editor-ui#235]
As a young person who is using starter projects
I want to be able to cut and paste my output code into input without any issues
So that I can make changes to my code

Tracy, in testing[ the Hello World project](https://editor.raspberrypi.org/python/python-emoji-example), has flagged that there is an issue when doing this with e.g. emojis/text where it is also pasting in additional whitespace. And in Windows creating a vertical scroll bar

**Tasks:**

- [ ] to check this can be supported across browsers
- [ ] change how the scroll bar is set (Windows and Mac do different things here, and it is likely fixed for Windows machines by setting it to "auto"
- [ ] having had a quick look on stand-up (thanks Steve) we think the whitespace cut and paste issue is down to the "span" class being used having unnecessary padding specified i.e. doubling up, and being part of what is cut and pasted in

**Example of issue:**
![image](https://user-images.githubusercontent.com/14887827/194369903-5b32a713-b245-4aae-b936-b3f9e86a4ffd.png)
