### ISSUE TITLE
Sidebar - info

### ISSUE THREAD

**Issue by sra405** [RaspberryPiFoundation/editor-ui#497]
As a user
I want to access general information in the sidebar/menu
So that I can learn more about the editor
[Design link](https://www.figma.com/file/SrINjD1MCT6VWYf1Yc9fV1/Code-Editor---Designs?mode=dev)

-------------

**Tasks**

- [x] Create information pane and add into `Sidebar` with correct icon
- [x] Add explanation bubble with the copy from the design
- [x] Add links and other info from footer
- [x] Remove existing footer

**ACs**
- [x] I can see the copy as per the design - **copy edit needed, use dummy copy as per design**
- [x] I can see the links as per the design (footer information, plus a link to the feedback form)

**Comment by sra405** [comment]
Not sure how much of the design is in/out of scope - consider use case

**Comment by sra405** [comment]
@loiswells97 to refine
