### ISSUE TITLE
Sidebar - settings

### ISSUE THREAD

**Issue by sra405** [RaspberryPiFoundation/editor-ui#506]
As a user
I want to access settings in the sidebar/menu
So that I can customise my workspace for coding

-------------

[Design that mirror existing functionality](https://www.figma.com/file/Rbn27JvH8A8wwqagKSReIq/Code-Editor---Component-library?type=design&node-id=1570-15992&mode=design&t=pL4wqCGdBcx1iU4j-4)

Agreed approach at this stage is to add to new sidebar, but implement only existing settings options.
Should re-use language selection radio button component.

**ACs**
- [ ] I can choose my theme - only light/dark
- [ ] I can input my text size - 3 choices  - S/R/L
  - Look at using css variables as per spike: https://github.com/RaspberryPiFoundation/editor-ui/issues/558
- [ ] My selections are saved automatically

Estimate of 3 is based on mirroring existing functionality.

**Tasks**
- [ ] Move existing functionality it to the sidebar

**Comment by sra405** [comment]
@danhalson to refine

**Comment by danhalson** [comment]
Blocked by: https://github.com/RaspberryPiFoundation/editor-ui/issues/558
