### ISSUE TITLE
Sidebar - projects

### ISSUE THREAD

**Issue by sra405** [RaspberryPiFoundation/editor-ui#508]
As a user
I want to see my overall project details 
So that I can view key information about my project and get to my other projects

-------------
[Design](https://www.figma.com/file/SrINjD1MCT6VWYf1Yc9fV1/Code-Editor---Designs?type=design&node-id=2044-119860&mode=design&t=YVmXyXL7OpNj4cV1-4)

**Tasks**

- [x] Create projects pane and add into the `Sidebar` component with correct icon
- [ ] Move `Your projects` link button into the projects pane and make it a primary button
- [x] Move Rename project input into the projects panel
- [x] Extract and display project data (project type and date created)
- [x] Move download button into projects pane and make it a secondary button

**ACs**
- [ ] Project name can be edited by clicking on the pencil. Otherwise it is a read-only field. 
- [ ] Project details are visible and accurate 
- [ ] User can download from here (don't include share in this iteration)

**Comment by sra405** [comment]
@loiswells97 to refine

**Comment by magdalenajadach** [comment]
merged and closed
