### ISSUE TITLE
Mobile code input view

### ISSUE THREAD

**Issue by MFarringtonRPF** [RaspberryPiFoundation/editor-ui#569]
As a user, I want to work on my code on my mobile, so that I can code on my preferred device.

[Design](https://www.figma.com/file/SrINjD1MCT6VWYf1Yc9fV1/Code-Editor---Designs?type=design&node-id=3009-79463&mode=design&t=aI6RVte6GXwvodaO-4)

**Tasks**
- [x] Create EditorInputTopBar component, and move tabs into it
- [x] Ensure scrolling behaviour as specified in design (fix the height issue with the URL bar covering part of the page resulting in scrolling)
- [x] RunBar appears in expected position in correct situations, could use container queries to toggle visibility in it's respective component
- [x] Add behaviour to toggle visible panel when `Run` clicked
- [x] Look at interaction behaviour (scrolling and pinch to zoom)

------
**Design questions**
- ~~Scrollbars: Does the user need to click the bar specifically, as otherwise it their keyboard will open? This might be handled by the device native gesture handling.~~

------
**General ACs for mobile**
- Account navigation follows whatever is the latest (out of scope for specific mobile support)
- Make sure the breakpoints are at the same width of the application
- Users cannot zoom in/out by pinching (since we have text resizing in the settings)
  - **Tech question:** Is this enabled by default, or something we have to disable? 
- ~~Auto-run/refresh is disabled on mobile.~~ We have not implemented this functionality.

**Story ACs**
- Mobile code input view follows the designs 
- Mobile code input view appears at the correct breakpoints
- I can see the bottom navigation (covered when the user has their keyboard open)
- I can see my project files in my top bar
- I can see the 'Run' button in my top bar
  - When clicked, I am taken to the preview/output view, so that I can see my code run
- I can see my project's name and when it was last saved above the main navigation
- When I click in the code panel, my native device keyboard appears
   - I can scroll vertically and horizontally (Note: we think what triggers a scroll vs keyboard opening will be handled by the the device, so the user shouldn't need to click the actual scrollbar, they should be able to scroll by swiping, just like how they should be able to scroll wth a trackpad or scrollwheel).

**Comment by maxelkins** [comment]
> Scrollbars: Does the user need to click the bar specifically, as otherwise it their keyboard will open? This might be handled by the device native gesture handling.

Is the concern that scrolling with focus the input and therefore open the keyboard? I'm fairly certain this should be handled by the the device too and shouldnt be an issue but needs to be tested. But no the user shouldn't HAVE TO click the actual scrollbar, they should be able to scroll by swiping, just like how they should be able to scroll wth a trackpad or scrollwheel.

**Comment by sra405** [comment]
Need to review against existing + ensure the mobile height is working correctly

**Comment by sra405** [comment]
separated out scroll fix with https://github.com/RaspberryPiFoundation/editor-ui/issues/627

**Comment by sra405** [comment]
@PetarSimonovic to quickly check designs with scroll behaviour

**Comment by PetarSimonovic** [comment]
Checked and it looks like the scroll behaves as it should

**Comment by sra405** [comment]
completed as part of other tickets in the milestone
