### ISSUE TITLE
Mobile output/preview view

### ISSUE THREAD

**Issue by MFarringtonRPF** [RaspberryPiFoundation/editor-ui#570]
As a user, I want to preview my code on my mobile, so that I can code on my preferred device.

[Main design](https://www.figma.com/file/SrINjD1MCT6VWYf1Yc9fV1/Code-Editor---Designs?type=design&node-id=3009-79464&mode=design&t=aI6RVte6GXwvodaO-4)

**Design questions**
- ~~If my code has been run, and then I move back into the Code view, then back to the Output view, should my previously run code still be there or a blank screen?~~
- ~~Python preview: how does the user exit the Output views and return to the Editor?~~
- ~~HTML preview: does clicking the arrow icon return the user to the Editor?~~
- ~~HTML preview: requirement is for "open in new tab to be hidden on mobile if not possible".  But how does the user generate a preview if the button is hidden?~~
- ~~Will there be any layout effects when the Run button changes to Stop? Eg, could this make the unselected Python tab too narrow?~~
  - The button width will increase slightly, this is fine.
- ~~General Q on Users cannot zoom in/out by pinching (since we have text resizing in the settings): Should we keep the standard mobile behaviour for pinching, for accessibility and user expected behaviour?~~
  - We will go with native device to start, unless there is an accessibility issue with this. 

------
**General ACs for mobile**
- Account navigation follows whatever is the latest (out of scope for specific mobile support)
- Make sure the breakpoints are at the same width of the application
- Users cannot zoom in/out by pinching (since we have text resizing in the settings)
  - **Tech question:** Is this enabled by default, or something we have to disable? 
- ~~Auto-run/refresh is disabled on mobile.~~ We have not implemented this functionality.

**Story ACs**
- Mobile code output view follows the designs 
- Mobile code output view appears at the correct breakpoints
- I can see the bottom navigation
- I can see the 'Run' button in my top bar
  - When clicked, I stay in the preview/output view and my code runs again
- If my code has not been run when I view the preview/output view, then I can see a blank view (see designs)
   - If my code has been run, and then I move back into the Code view, then back to the Output view, the previously run code should still be there. Just how on desktop the output remains there if you refocus the input.
- I can see my project's name and when it was last saved above the main navigation
- If the output is offscreen (due to hardcoded pixels), a scrollbar should appear and behave in the same way as the input view

When coding in Python:
- [x]  I can see two tabs for 'Visual output' and 'Text output' in my top bar
- [x]  I can choose from a stacked or tabbed view
- [ ] #638

When coding in HTML/CSS:
- [x] I can see my HTML files in my top bar
- [x] My HTM tab is named '[filename].html' 
- [x] I can open my preview in a new tab (uses native device functionality) is this is possible. We will hide the button if not possible on mobile/tablet.

------

**TASKS**

- [x] Header and footer should preserve the Editor's layout

**Python**
- [x] Create a "Tabbed View" that allows user to switch between Visual Output and Text Output
- [x]  Create a "Stacked View" that splits the screen horizontally, with Visual Output above Text Output
- [ ] Create a button that allows user to switch between the Tabbed and Stacked views. The button's icon should change accordingly
- [x] If there is no Visual output, the pane should display a dotted pattern

**HTML**
- [x] Create a preview pane that should be titled "{filename} preview"
- [x] If there is no Visual output, the pane should display a dotted pattern
- [x] "Open in new tab" to be hidden if possible (need to clarify this with design - see above?)

**Comment by maxelkins** [comment]
**Design questions**

> If my code has been run, and then I move back into the Code view, then back to the Output view, should my previously run code still be there or a blank screen?

Previous run code should still be there. Just how on desktop the output remains there if you refocus the input.

>Python preview: how does the user exit the Output views and return to the Editor?

Im not sure I understand this question. The user navigates between input/output using the bottom navigation.

>HTML preview: does clicking the arrow icon return the user to the Editor?

If you are referenceing the box with and arrow icon, this is the icon for opening in a new tab.
The full label for this button is seen in the component documentation [here](https://www.figma.com/file/Rbn27JvH8A8wwqagKSReIq/Code-Editor---Component-library?type=design&node-id=1657-28459&mode=design&t=teoArFOTvaZKWOtK-4). I think we previously disucssed if open in a new tab is not possible on mobile this option will be hidden on mobile.

>HTML preview: requirement is for "open in new tab to be hidden on mobile if not possible".  But how does the user generate a preview if the button is hidden?

Not sure I understand the question, this button is to 'open in new tab' not run the code. To run the clode the user clicks/taps the run button and the preview is shown below in the output panel as it does with desktop.

>Will there be any layout effects when the Run button changes to Stop? Eg, could this make the unselected Python tab too narrow?

The button width will increase slightly, this is fine.

>General Q on Users cannot zoom in/out by pinching (since we have text resizing in the settings): Should we keep the standard mobile behaviour for pinching, for accessibility and user expected behaviour?

I don't know what the accessibility best practice is but I suspect allowing pinch to zoom could cause usability issues - however I may be wrong. I'm also not sure if pinch to zoom will work if the input is focused - needs testing.

**Comment by MFarringtonRPF** [comment]
@magdalenajadach, could you add any insight on the pinching to zoom in/out from an accessibility perspective?

**Comment by MFarringtonRPF** [comment]
Closing this, as the remaining bits are covered in other stories under the milestone.
