### ISSUE TITLE
Initial project download sidebar panel

### ISSUE THREAD

**Issue by sra405** [RaspberryPiFoundation/editor-ui#740]
Initial structure and logic to show project download panel in the sidebar

[design](https://www.figma.com/file/SrINjD1MCT6VWYf1Yc9fV1/Code-Editor---Designs?type=design&node-id=3736-82222&mode=design&t=SWx7ejfxxOm7I0Oh-4)

**Functional ACs**
- [ ] When on projects site, Download tab always appears at the bottom of the sidebar
- [ ] ~Users can log in or sign up to the projects site using these buttons~ (https://github.com/RaspberryPiFoundation/editor-ui/issues/745)
  - [ ] ~They are then also logged into to Editor~ 
  - [ ] ~When logged in, their progress within the Project and their accompanying Editor code is saved, so that they can return to it~
 (Log in/Sign up ACs are implemented in ([#745])
- [ ] Users can download their editor project files, as in the standalone editor - they _cannot_ download the instructions as part of this

### Clarification

- [ ] Does the user log in to the projects site or the editor? (Logs in to projects, saves remixes to editor)
- [ ] What does the user see if the are logged in instead of "Log in to save your progress"? 

### Tasks
- [x] Implement the download functionality, repurposing/reusing the existing code for the standalone editor

**Comment by sra405** [comment]
To help with some of the questions raised:
- The user will only be able to log in via the host application (so the projects site for this case) and this is passed to the web component (see https://github.com/RaspberryPiFoundation/editor-ui/issues/722) so we'll probably need custom events to trigger the log in/sign up flow on the host.
- I imagine that whole "log in to save your progress" is conditional and isn't shown but may need @maxelkins to clarify

**Comment by MFarringtonRPF** [comment]
@PetarSimonovic @maxelkins, I have updated the functional ACs. Please lmk if there is anything missing or unclear.
