### ISSUE TITLE
Initial project instructions sidebar panel

### ISSUE THREAD

**Issue by sra405** [RaspberryPiFoundation/editor-ui#741]
Initial structure and logic to show project instructions in the sidebar

[design](https://www.figma.com/file/SrINjD1MCT6VWYf1Yc9fV1/Code-Editor---Designs?type=design&node-id=3736-82218&mode=design&t=SWx7ejfxxOm7I0Oh-4)

- Implementation follows the design and all notes
- This story includes the progress bar, but not rendering all the content inside (instructions)
- Step-tracking is aligned to this functionality

**Functional ACs**
- [ ] When on projects site, Instructions tab always appears at the top of the sidebar
- [ ] Users can click forwards and backwards through the steps
- [ ] The progress bar shows a user's % progress through all steps in that project
- [ ] The tab shows the content for the current step in the project
- [ ] ~~When users return to a project, or navigate back to the instructions tab from within the project, they are taken back to the same project step in the Instructions tab~~ - **to be added somewhere else later**

**Comment by PetarSimonovic** [comment]
### Tasks

#### Content panel

- [ ] The panel should display the content for the current step in the project.`instructions` and `currentStep` are passed through to the WebComponent from the Projects site. `instructions` contain `contents`, a collection of objects that align with the `currentStep`.  No need to render the step content properly for now: just dump the json into the panel.

#### Progress bar

Build the projects bar elements in line with the designs:
- [ ] Forward button (could use the editor's `icons/chevron_right.svg`)
- [ ] Back button (could use the `icons/chevron_left.svg`)
- [ ] The progress bar (potentially using the [native HTML progress](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/progress) element)

Add step-tracking functionality to the progress bar:
- [ ] Clicking forward should increment the step
- [ ] Clicking back should decrement the step
- [ ] The change in step should display the correct content in the content panel
- [ ] The progress bar should notify the Projects site of any changes.  the `stepChangedEvent` listener already exists to handle this but must be integrated with the buttons
 **TBC**: awaiting clarification on button styling for active and disabled (ie first and last step) button states

**Comment by sra405** [comment]
@MFarringtonRPF this is just the initial structure of the sidebar panel so the last AC is out of scope:
```
When users return to a project, or navigate back to the instructions tab from within the project, they are taken back to the same project step in the Instructions tab
```

**Comment by MFarringtonRPF** [comment]
OK sure @sra405 - not sure where to put it, so feel free to move when it makes sense!
