### ISSUE TITLE
Code snippet instructions styling

### ISSUE THREAD

**Issue by sra405** [RaspberryPiFoundation/editor-ui#764]
[design](https://www.figma.com/file/SrINjD1MCT6VWYf1Yc9fV1/Code-Editor---Designs?type=design&node-id=3784-67543&mode=design&t=QL7uMlJyVSuhnWbh-4)

### Tasks

- [ ] Identify the current classes added to similar project site projects
- [ ] Determine if these are fit for purpose in this case
- [ ] If not fit for purpose manually add the classnames in the simplified project files in github and remake the project to pass them through to the web component
- [ ] Add the required classes to the web component to style them in line with design
- [ ] Add docs in the editor-ui with a little snippet

Parent ticket - https://github.com/RaspberryPiFoundation/editor-ui/issues/732
